Configure system-wide paths at build time
DadSchoorse/vkBasalt pull request #123
Opened 2020-11-10 11:24 UTC by gasinvein

Hardcoded `/etc` and `/usr/share` paths might work for most cases, but are invalid for distribution with other install prefix, like in flatpak packages or NixOS. Let meson configure the paths instead of using static values.

2020-11-13 19:25 UTC, stephanlachnit approved these changes

2020-11-18 00:38 UTC, TheEvilSkeleton approved these changes

2020-11-18 18:39 UTC, DadSchoorse requested changes

2020-11-18 18:39 UTC, DadSchoorse commented on src/config.cpp
> -            "/usr/local/share/vkBasalt/vkBasalt.conf", // legacy system-wide config (alternative)
Please align the other comments.

2020-11-18 19:25 UTC, gasinvein commented on src/config.cpp
> -            "/usr/local/share/vkBasalt/vkBasalt.conf", // legacy system-wide config (alternative)
Done.

2020-11-18 19:36 UTC, DadSchoorse requested changes

2020-11-18 19:36 UTC, DadSchoorse commented on src/config.cpp
>          const std::array<std::string, 8> configPath = {
The size is now 7.

2020-11-18 19:40 UTC, gasinvein commented on src/config.cpp
>          const std::array<std::string, 8> configPath = {
Fixed.

2020-11-18 20:11 UTC, merged